site_name: When immunology meets bioinformatics

nav:
  - Home: index.md
  - Precourse preparations: precourse.md
  - Course schedule: course_schedule.md
  - Course material: course_material.md
  - Hands-on: hands_on.md

theme:
  name: material
  logo: assets/SIB_logo.svg
  favicon: assets/SIB_logo.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    tip: fontawesome/solid/bullhorn
  features:
    - announce.dismiss

# Repository
repo_name: sib-swiss/immunology-in-bioinformatics-training/
repo_url: https://github.com/sib-swiss/immunology-in-bioinformatics-training

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  
copyright: >
  Copyright &copy; 2021-2022 SIB Swiss institute of Bioinformatics –
